const projectData = [
  {
    projectId: 1,
    type: "fullstack",
    featured: true,
    title: "Human Rights First: Blue Witness",
    img: 0,
    imgAlt: "project image",
    description: "Worked on an legacy project built by past developers and reported to a stakeholder with ideas and designs. Worked with a team of 7 web developers, including a lead designer, and 3 data scientists.",
    repoLink: "",
    deployedSite: "",
    blog: "https://robert-petersen.medium.com/my-first-experience-with-a-legacy-project-496c6146810",
  },
  {
    projectId: 2,
    type: "fullstack",
    featured: true,
    title: "NASA Photos",
    img: 1,
    imgAlt: "project image",
    description: "Website that searches and displays photos from the NASA Astronomy Photo of the Day API. Built using React, SASS, React-scroll and React-icons.",
    repoLink: "https://github.com/robert-petersen/shopify-nasa-challenge",
    deployedSite: "https://shopify-nasa-challenge-zeta.vercel.app/",
    blog: "",
  },
  {
    projectId: 3,
    type: "frontend",
    featured: true,
    title: "Calculator App",
    img: 2,
    imgAlt: "project image",
    description: "This is my solution to the Calculator app challenge on Frontend Mentor. Frontend Mentor challenges help you improve your coding skills by building realistic projects. Created using React, Redux, SASS, and CSS Grids.",
    repoLink: "https://github.com/robert-petersen/calculator-app",
    deployedSite: "https://roberts-calculator-app.vercel.app/",
    blog: "",
  },
  {
    projectId: 4,
    type: "frontend",
    featured: true,
    title: "Rock Paper Scissors",
    img: 3,
    imgAlt: "project image",
    description: "An application to play rock paper scissors. Created using React, Styled Components, and React Icons.",
    repoLink: "https://github.com/robert-petersen/rock-paper-scissors",
    deployedSite: "https://rock-paper-scissors-wine.vercel.app/",
    blog: "",
  },
  {
    projectId: 5,
    type: "frontend",
    featured: true,
    title: "Banking Website",
    img: 4,
    imgAlt: "project image",
    description: "Created a basic banking website using React, Styled Components, React Scroll, and React Icons. Application deployed using Vercel.",
    repoLink: "https://github.com/robert-petersen/smooth-scroll-styled-components",
    deployedSite: "https://smooth-scroll-styled-components.vercel.app/",
    blog: "",
  },
  {
    projectId: 6,
    type: "frontend",
    featured: true,
    title: "Pizza Website",
    img: 5,
    imgAlt: "project image",
    description: "Created a basic pizza website using React, Redux for state management, Styled Components, React Scroll, and React Icons. Application deployed using Vercel.",
    repoLink: "https://github.com/robert-petersen/pizza-website",
    deployedSite: "https://pizza-website-one.vercel.app/",
    blog: "",
  },
  {
    projectId: 7,
    type: "backend",
    featured: true,
    title: "Food Truck Backend",
    img: 6,
    imgAlt: "project image",
    description: "Created a database for a food truck application using Node.js, Express, Knex, SQLite3, bcryptjs, JWT, and deployment on Heroku.",
    repoLink: "https://github.com/robert-petersen/food-truck-database",
    deployedSite: "",
    blog: "",
  },
  {
    projectId: 8,
    type: "backend",
    featured: true,
    title: "School in the Cloud Backend",
    img: 7,
    imgAlt: "project image",
    description: "Created a database for a school task management application using Node.js, Express, Knex, SQLite3, bcryptjs, JWT, and deployment on Heroku. Lead a team of 5 developers for this project.",
    repoLink: "https://github.com/School-In-The-Cloud-LambdaSchool/SchoolDB",
    deployedSite: "",
    blog: "",
  },
]